#ifndef __RetimerAboutDialog__
#define __RetimerAboutDialog__

/**
@file
Subclass of AboutDialog, which is generated by wxFormBuilder.
*/

#include "retimer_wx.h"

/** Implementing AboutDialog */
class RetimerAboutDialog : public AboutDialog {
	protected:
		// Handlers for AboutDialog events.
		void OnOKClick(wxCommandEvent& event);

	public:
		RetimerAboutDialog(wxWindow* parent);
};

#endif // __RetimerAboutDialog__
