#ifndef __RetimerPrefsDialog__
#define __RetimerPrefsDialog__

#include "../marker.h"
#include "../sample.h"
#include "../curve.h"

#include "retimer_wx.h"
#include <iostream>

/**
@file
Subclass of PrefsDialog, which is generated by wxFormBuilder.
*/

/** Implementing PrefsDialog */
class RetimerPrefsDialog : public PrefsDialog {
protected:
	// Handlers for PrefsDialog events.
	void OnIntModeChange(wxCommandEvent& event);
	void OnCheckShowInt(wxCommandEvent& event);
	void OnStretchModeChange(wxCommandEvent& event);
	void OnTempoEnter(wxCommandEvent& event);
	void OnBeatResEnter(wxCommandEvent& event);
	void OnOKClick(wxCommandEvent& event);
	void OnCancelClick(wxCommandEvent& event);

	int oldInterpolationMode;
	bool oldShowIntLine;
	int oldStretchMode;
	int oldTempo;
	float oldBeatResolution;

	Marker* marker;
	Sample* sample;
	Curve* curve;

public:
	/** Constructor */
	RetimerPrefsDialog(Marker* m, Sample* s, Curve* c);
};

#endif // __RetimerPrefsDialog__
