#ifndef __xiRTPrefsDialog__
#define __xiRTPrefsDialog__

#include "../marker.h"
#include "../sample.h"
#include "../curve.h"

/**
@file
Subclass of PrefsDialog, which is generated by wxFormBuilder.
*/

#include "xiRetimer_wxfb.h"

/** Implementing PrefsDialog */
class xiRTPrefsDialog : public PrefsDialog
{
protected:
	// Handlers for PrefsDialog events.
	void OnIntModeChange( wxCommandEvent& event );
	void OnStretchModeChange( wxCommandEvent& event );
	void OnTempoEnter( wxCommandEvent& event );
	void OnBeatResEnter( wxCommandEvent& event );
	void OnOKClick( wxCommandEvent& event );
	void OnCancelClick( wxCommandEvent& event );

  int oldInterpolationMode;
  int oldStretchMode;
  int oldTempo;
  float oldBeatResolution;

  Marker* marker;
  Sample* sample;
  Curve* curve;
	
public:
	/** Constructor */
	xiRTPrefsDialog(Marker* m, Sample* s, Curve* c);
};

#endif // __xiRTPrefsDialog__
