#ifndef __xiRTMainFrame__
#define __xiRTMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "xiRetimer_wxfb.h"
#include "../src/sample.h"
#include "../src/curve.h"


/** Implementing MainFrame */
class xiRTMainFrame : public MainFrame
{
protected:
  // Handlers for MainFrame events.
  void OnLeftDown( wxMouseEvent& event );
  void OnLeftUp( wxMouseEvent& event );
  void OnLeftDClick( wxMouseEvent& event );
  void OnMotion( wxMouseEvent& event );
  void OnOpenClick( wxCommandEvent& event );
  void OnExportClick( wxCommandEvent& event );
  void OnPrefsClick( wxCommandEvent& event );
  void OnExitClick( wxCommandEvent& event );
  void OnHelpClick( wxCommandEvent& event );
  void OnAboutClick( wxCommandEvent& event );
  void OnProcessClick( wxCommandEvent& event );
  void OnMSetClick( wxCommandEvent& event );
  void OnMRmClick( wxCommandEvent& event );
  void OnUpdateUI( wxUpdateUIEvent& event );
  void paint();
  static const int MARKERWIDTH=15;
  
  Sample* sample;
  Curve* curve;
  int width;
  bool Marker_move;
	
public:
	/** Constructor */
	xiRTMainFrame( wxWindow* parent );
	~xiRTMainFrame(  );
};

#endif // __xiRTMainFrame__
