#ifndef __xiRTFileSelectDialog__
#define __xiRTFileSelectDialog__

/**
@file
Subclass of FileSelectDialog, which is generated by wxFormBuilder.
*/

#include "xiRetimer_wxfb.h"

/** Implementing FileSelectDialog */
class xiRTFileSelectDialog : public FileSelectDialog
{
protected:
	// Handlers for FileSelectDialog events.
	void OnOKClick( wxCommandEvent& event );
	void OnCancelClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	xiRTFileSelectDialog( wxWindow* parent );
};

#endif // __xiRTFileSelectDialog__
